title: Santhosh Paval
logo: [![Project Image](https://github.com/SanthoshPaval/Data-Analytics-Portfolio/blob/main/Beige%20Simple%20Photo%20Signature%20Twitter%20Profile%20Picture.png)
description : Here's a look at my Data Science Portfolio :)
#show_downloads: true
theme: jekyll-theme-minimal
