title: Santhosh Paval
logo: ![Santhosh Paval Logo](https://github.com/SanthoshPaval/Data-Analytics-Portfolio/raw/35ed47a2b9dd3df70509ebf8f26771d4b90c75a7/Beige%20Simple%20Photo%20Signature%20Twitter%20Profile%20Picture.png)
description : Here's a look at my Data Science Portfolio :)
#show_downloads: true
theme: jekyll-theme-minimal
